### ISSUE TITLE
Problem with saving domains

### ISSUE THREAD

**Issue by BenjaminNSD** [DASISH/qddt-client#121]
@StigNorland 

It's currently not possible to save new response domains (tried it for scale and code domain). I still can edit name and description of an existing domain, but I can't alter the codes and categories permanently. They disappear after submitting the domain.

**Comment by StigNorland** [comment]
when saving lists, inputlimit needs to be updated with "number of codes"
and children collection updated with the selected "categories"

**Comment by liuy97** [comment]
What's the problem here? I can edit a scale domain for change codes and categories.

**Comment by BenjaminNSD** [comment]
Try to create a new scale and then try to reuse them in a new question item. Doesn't work.

Response domains which I create on https://qddt.nsd.no/ or http://liuy97.github.io/ are currently not saved. They disappear from the list when you logout and login again.

**Comment by liuy97** [comment]
What I did:
1. create a scale domain for this issue.
2. reuse it.
3. edit codes
4. goto question items
5. logout/login

Which step will have this problem?

**Comment by BenjaminNSD** [comment]
It's still the same problem, but I can see the new scale you saved for this issue. It looks as if you can save domains while I can't. I work on http://liuy97.github.io/Responsedomains and   https://qddt.nsd.no/ 

 "4." When I go to question items I can't reuse the scale which I submitted before. when I then go back to scale domain my scale has disappeared.

**Comment by liuy97** [comment]
Which browser did you use? I have tested for creating scale domain in http://liuy97.github.io/ with my username and admin. It works at both cases. My browser is chrome.

**Comment by BenjaminNSD** [comment]
CHROME

**Comment by liuy97** [comment]
@StigNorland ,

Could you check the response domain with id (7f000101-568e-1379-8156-b6aec703007c) in the database? It is not included in the result when searching scale domains (https://qddt.nsd.no/api/responsedomain/page/search?ResponseKind=SCALE).

**Comment by StigNorland** [comment]
That certainly seems like a bug in the backend.

**Comment by StigNorland** [comment]
Since the api searches through name and description with %, a null field will not generate a hit, I have made description none nullable. a ""string is still valid. (and I think that is fixed in the backend now

**Comment by liuy97** [comment]
Fixed.

**Comment by BenjaminNSD** [comment]
I still can't change the response domain and keep the changes.

Example. I edit a codedomain with the name TVTOT. Then I reduce the number of codes from 9 to 8. Then I save TVTOT. In preview it looks fine, but after refreshing the old version appears again.

**Comment by BenjaminNSD** [comment]
We should reopen issue until this is solved

**Comment by liuy97** [comment]
@StigNorland 
When I reduce the number of anchors of a scale domain, say from 2 anchors to 1, the categories are transferred to the backend correctly. However, the backend still returns a scale domain with 2 anchors.

**Comment by BenjaminNSD** [comment]
Will it be possible to remove codes/categories from a codedomain and save them permanently in the release today?

**Comment by StigNorland** [comment]
Not fixed for 26.08 release
